# Generated by Django 4.2 on 2023-05-17 09:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='car')),
                ('brand', models.CharField(max_length=50)),
                ('inventory', models.PositiveIntegerField()),
                ('year_Manufacture', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2023)])),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('category', models.CharField(choices=[('New', 'New'), ('Used', 'Used')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
