# Generated by Django 4.2 on 2023-05-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='category',
            field=models.CharField(choices=[('Used', 'Used'), ('New', 'New')], max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='year_Manufacture',
            field=models.IntegerField(),
        ),
    ]
