# Generated by Django 4.2 on 2023-05-17 09:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_alter_car_category_alter_car_year_manufacture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='category',
            field=models.CharField(choices=[('New', 'New'), ('Used', 'Used')], max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='created_at',
            field=models.DateTimeField(default=datetime.date(2021, 12, 18)),
        ),
    ]
