# Generated by Django 4.2 on 2023-05-22 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0006_customer_remove_carbooking_email_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarBooking',
            new_name='CarRental',
        ),
    ]
