# Generated by Django 4.2 on 2023-05-24 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('rentals', '0010_customer_user_alter_car_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrental',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
