# Generated by Django 4.2 on 2023-05-24 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0011_alter_carrental_customer_delete_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='category',
            field=models.CharField(choices=[('New', 'New'), ('Used', 'Used')], max_length=50),
        ),
    ]
