# Generated by Django 4.2 on 2023-05-24 13:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0012_alter_car_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrental',
            name='created_at',
            field=models.DateTimeField(default=datetime.date(2021, 12, 18)),
        ),
        migrations.AlterField(
            model_name='car',
            name='category',
            field=models.CharField(choices=[('Used', 'Used'), ('New', 'New')], max_length=50),
        ),
    ]
