# Generated by Django 4.2 on 2023-05-24 13:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0013_carrental_created_at_alter_car_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='category',
            field=models.CharField(choices=[('New', 'New'), ('Used', 'Used')], max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='created_at',
            field=models.DateTimeField(default=datetime.date(2023, 5, 24)),
        ),
        migrations.AlterField(
            model_name='carrental',
            name='created_at',
            field=models.DateTimeField(default=datetime.date(2023, 5, 24)),
        ),
    ]
