# Generated by Django 4.2 on 2023-05-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0014_alter_car_category_alter_car_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='carrental',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
