# Generated by Django 4.2 on 2023-05-25 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0015_alter_car_created_at_alter_carrental_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrental',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
