# Generated by Django 4.2 on 2023-05-16 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='CarCategory',
        ),
        migrations.RenameModel(
            old_name='Product',
            new_name='CarProduct',
        ),
    ]
